let
    Origen = Excel.Workbook(File.Contents("D:\SkyDrive Pro\OneDrive\03. Formación\UOC. Máster Data Science\M2.859 Visualización de Datos\A7. Proyecto de visualización. El informe de proyecto. (PEC3)\Datos\pax_all_agreements_data.xlsx"), null, true),
    #"Peace Agreements_Sheet" = Origen{[Item="Peace Agreements",Kind="Sheet"]}[Data],
    #"Encabezados promovidos" = Table.PromoteHeaders(#"Peace Agreements_Sheet", [PromoteAllScalars=true]),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Con", type text}, {"Contp", type text}, {"PP", Int64.Type}, {"PPName", type text}, {"Reg", type text}, {"AgtId", Int64.Type}, {"Agt", type text}, {"Dat", type date}, {"Status", type text}, {"Lgt", Int64.Type}, {"N_characters", Int64.Type}, {"Agtp", type text}, {"Stage", type text}, {"StageSub", type text}, {"Part", type text}, {"ThrdPart", type text}, {"OthAgr", type text}, {"Loc1ISO", type text}, {"Loc2ISO", type text}, {"Loc1GWNO", Int64.Type}, {"Loc2GWNO", Int64.Type}, {"UcdpCon", type any}, {"UcdpAgr", type any}, {"PamAgr", type any}, {"CowWar", type any}, {"GCh", Int64.Type}, {"GChRhet", Int64.Type}, {"GChAntid", Int64.Type}, {"GChSubs", Int64.Type}, {"GChOth", Int64.Type}, {"GDis", Int64.Type}, {"GDisRhet", Int64.Type}, {"GDisAntid", Int64.Type}, {"GDisSubs", Int64.Type}, {"GDisOth", Int64.Type}, {"GAge", Int64.Type}, {"GAgeRhet", Int64.Type}, {"GAgeAntid", Int64.Type}, {"GAgeSubs", Int64.Type}, {"GAgeOth", Int64.Type}, {"GMig", Int64.Type}, {"GMigRhet", Int64.Type}, {"GMigAntid", Int64.Type}, {"GMigSubs", Int64.Type}, {"GMigOth", Int64.Type}, {"GRa", Int64.Type}, {"GRaRhet", Int64.Type}, {"GRaAntid", Int64.Type}, {"GRaSubs", Int64.Type}, {"GRaOth", Int64.Type}, {"GRe", Int64.Type}, {"GReRhet", Int64.Type}, {"GReAntid", Int64.Type}, {"GReSubs", Int64.Type}, {"GReOth", Int64.Type}, {"GInd", Int64.Type}, {"GIndRhet", Int64.Type}, {"GIndAntid", Int64.Type}, {"GIndSubs", Int64.Type}, {"GIndOth", Int64.Type}, {"GOth", Int64.Type}, {"GOthRhet", Int64.Type}, {"GOthAntid", Int64.Type}, {"GOthSubs", Int64.Type}, {"GOthOth", Int64.Type}, {"GRef", Int64.Type}, {"GRefRhet", Int64.Type}, {"GRefSubs", Int64.Type}, {"GRefOth", Int64.Type}, {"GSoc", Int64.Type}, {"GSocRhet", Int64.Type}, {"GSocAntid", Int64.Type}, {"GSocSubs", Int64.Type}, {"GSocOth", Int64.Type}, {"GeWom", Int64.Type}, {"GeMe", Int64.Type}, {"GeMeNu", Int64.Type}, {"GeMeOth", Int64.Type}, {"GeLgbti", Int64.Type}, {"GeLgbtiPos", Int64.Type}, {"GeLgbtiNeg", Int64.Type}, {"GeFa", Int64.Type}, {"StDef", Int64.Type}, {"StGen", Int64.Type}, {"StCon", Int64.Type}, {"StSd", Int64.Type}, {"StRef", Int64.Type}, {"StSym", Int64.Type}, {"StInd", Int64.Type}, {"StUni", Int64.Type}, {"StBor", Int64.Type}, {"StXbor", Int64.Type}, {"Pol", Int64.Type}, {"PolGen", Int64.Type}, {"PolNewInd", Int64.Type}, {"PolNewTemp", Int64.Type}, {"ConRen", Int64.Type}, {"Cons", Int64.Type}, {"Ele", Int64.Type}, {"ElecComm", Int64.Type}, {"PolPar", Int64.Type}, {"PolParTrans", Int64.Type}, {"PolParOth", Int64.Type}, {"Civso", Int64.Type}, {"Tral", Int64.Type}, {"Pubad", Int64.Type}, {"Polps", Int64.Type}, {"PpsSt", Int64.Type}, {"PpsSub", Int64.Type}, {"PpsEx", Int64.Type}, {"PpsOro", Int64.Type}, {"PpsOthPr", Int64.Type}, {"PpsVet", Int64.Type}, {"PpsAut", Int64.Type}, {"PpsInt", Int64.Type}, {"PpsOth", Int64.Type}, {"Terps", Int64.Type}, {"TpsSub", Int64.Type}, {"TpsLoc", Int64.Type}, {"TpsAut", Int64.Type}, {"TpsOth", Int64.Type}, {"Eps", Int64.Type}, {"EpsRes", Int64.Type}, {"EpsFis", Int64.Type}, {"EpsOth", Int64.Type}, {"Mps", Int64.Type}, {"MpsMe", Int64.Type}, {"MpsJt", Int64.Type}, {"MpsPro", Int64.Type}, {"MpsOth", Int64.Type}, {"HrGen", Int64.Type}, {"EqGen", Int64.Type}, {"HrDem", Int64.Type}, {"Prot", Int64.Type}, {"ProtCiv", Int64.Type}, {"ProtGrp", Int64.Type}, {"ProtLgl", Int64.Type}, {"ProtOth", Int64.Type}, {"HrFra", Int64.Type}, {"HrfSp", Int64.Type}, {"HrfBor", Int64.Type}, {"HrfTinc", Int64.Type}, {"HrfOth", Int64.Type}, {"HrCp", Int64.Type}, {"CprLife", Int64.Type}, {"CprTort", Int64.Type}, {"CprEq", Int64.Type}, {"CprSlav", Int64.Type}, {"CprLib", Int64.Type}, {"CprDet", Int64.Type}, {"CprFmov", Int64.Type}, {"CprFspe", Int64.Type}, {"CprFass", Int64.Type}, {"CprTria", Int64.Type}, {"CprPriv", Int64.Type}, {"CprVote", Int64.Type}, {"CprReli", Int64.Type}, {"CprOth", Int64.Type}, {"HrSec", Int64.Type}, {"SerProp", Int64.Type}, {"SerWork", Int64.Type}, {"SerHeal", Int64.Type}, {"SerEdu", Int64.Type}, {"SerStdl", Int64.Type}, {"SerShel", Int64.Type}, {"SerSs", Int64.Type}, {"SerCult", Int64.Type}, {"SerOth", Int64.Type}, {"HrNi", Int64.Type}, {"HrNiMe", Int64.Type}, {"HrNiNe", Int64.Type}, {"HrNiOth", Int64.Type}, {"HrIi", Int64.Type}, {"HrIiMon", Int64.Type}, {"HrIiBod", Int64.Type}, {"HrIiOth", Int64.Type}, {"HrMob", Int64.Type}, {"HrDet", Int64.Type}, {"Med", Int64.Type}, {"MedGov", Int64.Type}, {"MedSubs", Int64.Type}, {"MedLog", Int64.Type}, {"MedOth", Int64.Type}, {"HrCit", Int64.Type}, {"CitGen", Int64.Type}, {"CitRights", Int64.Type}, {"CitDef", Int64.Type}, {"CitOth", Int64.Type}, {"JusCr", Int64.Type}, {"JusCrSp", Int64.Type}, {"JusCrSys", Int64.Type}, {"JusCrPow", Int64.Type}, {"JusEm", Int64.Type}, {"JusJu", Int64.Type}, {"JusPri", Int64.Type}, {"JusTra", Int64.Type}, {"Dev", Int64.Type}, {"DevSoc", Int64.Type}, {"DevHum", Int64.Type}, {"DevInfra", Int64.Type}, {"NEC", Int64.Type}, {"NatRes", Int64.Type}, {"IntFu", Int64.Type}, {"Bus", Int64.Type}, {"Tax", Int64.Type}, {"TaxPo", Int64.Type}, {"TaxRef", Int64.Type}, {"TaxOth", Int64.Type}, {"Ban", Int64.Type}, {"CenBan", Int64.Type}, {"BanPers", Int64.Type}, {"BanInt", Int64.Type}, {"BanXb", Int64.Type}, {"LaRef", Int64.Type}, {"LaRefMan", Int64.Type}, {"LaRefRet", Int64.Type}, {"LaRefOth", Int64.Type}, {"LaNom", Int64.Type}, {"LaCH", Int64.Type}, {"LaCHTa", Int64.Type}, {"LaCHIt", Int64.Type}, {"LaCHPro", Int64.Type}, {"LaCHOth", Int64.Type}, {"LaEn", Int64.Type}, {"Wat", Int64.Type}, {"SsrGua", Int64.Type}, {"Ce", Int64.Type}, {"CeProv", Int64.Type}, {"CeGen", Int64.Type}, {"SsrPol", Int64.Type}, {"SsrArm", Int64.Type}, {"SsrDdr", Int64.Type}, {"DdrDemil", Int64.Type}, {"DdrProg", Int64.Type}, {"SsrInt", Int64.Type}, {"SsrPsf", Int64.Type}, {"SsrFf", Int64.Type}, {"Cor", Int64.Type}, {"SsrCrOcr", Int64.Type}, {"SsrDrugs", Int64.Type}, {"Terr", Int64.Type}, {"TjGen", Int64.Type}, {"TjAm", Int64.Type}, {"TjAmPro", Int64.Type}, {"TjSan", Int64.Type}, {"TjPower", Int64.Type}, {"TjAmBan", Int64.Type}, {"TjCou", Int64.Type}, {"TjJaNc", Int64.Type}, {"TjJaIc", Int64.Type}, {"TjMech", Int64.Type}, {"TjPrire", Int64.Type}, {"TjVet", Int64.Type}, {"TjVic", Int64.Type}, {"TjMis", Int64.Type}, {"TjRep", Int64.Type}, {"TjRSym", Int64.Type}, {"TjRMa", Int64.Type}, {"TjNR", Int64.Type}, {"ImUN", Int64.Type}, {"ImOth", Int64.Type}, {"ImRef", Int64.Type}, {"ImPK", Int64.Type}, {"ImE", Int64.Type}, {"ImSrc", Int64.Type}, {"Column266", type any}, {"Column267", type any}, {"Column268", type any}, {"Column269", type any}, {"Column270", type any}, {"Column271", type any}, {"Column272", type any}, {"Column273", type any}, {"Column274", type any}, {"Column275", type any}, {"Column276", type any}, {"Column277", type any}, {"Column278", type any}, {"Column279", type any}, {"Column280", type any}, {"Column281", type any}, {"Column282", type any}, {"Column283", type any}, {"Column284", type any}, {"Column285", type any}, {"Column286", type any}}),
    #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado", {"Con", "Contp", "PP", "PPName", "Reg", "AgtId", "Agt", "Dat", "Status", "Lgt", "N_characters", "Agtp", "Stage", "StageSub", "Part", "ThrdPart", "OthAgr", "Loc1ISO", "Loc2ISO", "Loc1GWNO", "Loc2GWNO", "UcdpCon", "UcdpAgr", "PamAgr", "CowWar"}, "Atributo", "Valor"),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Otras columnas con anulación de dinamización",{{"Atributo", "Variable"}}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Con", type text}}),
    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado1", each true),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Filas filtradas",{{"Valor", Int64.Type}}),
    #"Consultas combinadas" = Table.NestedJoin(#"Tipo cambiado2", {"Variable"}, #"Maestro Variables", {"Encabezado Original"}, "Maestro Variables", JoinKind.LeftOuter),
    #"Se expandió Maestro Variables" = Table.ExpandTableColumn(#"Consultas combinadas", "Maestro Variables", {"Columna Final", "Categoría_1", "Categoría_2", "Nivel"}, {"Columna Final", "Categoría_1", "Categoría_2", "Nivel"}),
    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Se expandió Maestro Variables",{{"Nivel", "Nivel_Variable"}}),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas con nombre cambiado2",{{"Columna Final", "Variable Largo"}, {"Con", "Con: Country/Entity"}, {"Contp", "Contp: Conflict type"}, {"PP", "PP: Peace Process Number"}, {"PPName", "PPName: Peace Process Name"}, {"Reg", "Reg: Region"}, {"AgtId", "AgtId: Agreement ID"}, {"Agt", "Agt: Agreement Name"}, {"Dat", "Dat: Date Signed"}, {"Status", "Status: Agreement Definition and Status"}, {"Lgt", "Lgt: Agreement length (pages)"}, {"N_characters", "N_characters: Agreement length (characters)"}, {"Agtp", "Agtp: Agreement/conflict type"}, {"Stage", "Stage: Agreement stage"}, {"StageSub", "StageSub: subcoding of stage"}, {"Part", "Part: Parties"}, {"ThrdPart", "ThrdPart: Third Parties"}, {"OthAgr", "OthAgr: Other Agreement"}, {"UcdpCon", "UcdpCon: Uppsala Conflict Data Program Conflict ID"}, {"UcdpAgr", "UcdpAgr: Uppsala Conflict Data Program peace agreement ID"}, {"PamAgr", "PamAgr: Kroc Institute’s Peace Accords Matrix agreement ID"}, {"CowWar", "CowWar: Correlates of war"}}),
    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"Nivel_Variable", Int64.Type}})
in
    #"Tipo cambiado3"